spring:
  application:
    name: nova # 애플리케이션 이름 설정
  config:
    import: optional:classpath:config/secrets.yaml #secrets.yaml 파일로 값 읽어오기
  datasource:
    url: jdbc:mysql://${DB_IP}:${DB_PORT}/${DB_TABLE}?serverTimezone=Asia/Seoul # DB 접속 URL (Timezone: Asia/Seoul)
    username: ${DB_USER} # DB 사용자 계정
    password: ${DB_PW} # DB 비밀번호
  sql:
    init:
      mode: always # 애플리케이션 시작 시 SQL 스크립트 실행 모드 (always: 항상 실행, never: 실행 x)
  jpa:
    defer-datasource-initialization: true
    show-sql: true # 실행되는 SQL 쿼리를 콘솔에 출력
    hibernate:
      ddl-auto: create # DDL 자동 생성 전략 (none / create / validate / update)
    properties:
      hibernate:
        format_sql: true # 로그에 출력되는 SQL을 보기 좋게 포맷팅
  mqtt:
    url: tcp://${MQTT_BROKER_IP}:${MQTT_PORT}
    client-id: ${CLIENT_ID}
    topic:
      device: hdc/device/+/safety/data, hdc/device/+/env/data, hdc/+/assistant/execute/res
  ai:
    google:
      genai:
        api-key: ${GOOGLE_API_KEY}
        project-id: ${GOOGLE_PROJECT_ID}
        chat:
          options:
            model: gemini-2.5-flash
# Swagger (SpringDoc) 설정
springdoc:
  swagger-ui:
    enabled: true               # Swagger UI 사용 활성화
    path: /api        # Swagger UI 접속 경로 (기본 경로 외 커스텀 경로)
    tags-sorter: alpha          # API 태그(Controller) 정렬 순서 (alpha: 알파벳순)
    operations-sorter: alpha    # API 오퍼레이션(Method) 정렬 순서 (alpha: 알파벳순)
# jwt Token
jwt:
  secret: ${JWT_TOKEN}
